### PR TITLE
Add test showcasing compilation issue on equality expectations (latest master)

### PR DESCRIPTION
**Pull request by acecilia**
Hi 👋 

This PR showcases compilation errors when using equality expectations, showing up in latest master.
These issues are not present in latest release v9.2.1

### CODE REVIEW

**Comment by ikesyo** [comment]
Might be related to #897 and/or #907.

File: Tests/NimbleTests/Matchers/EqualTest.swift [hunk 1]
```diff
@@ -40,6 +40,44 @@ final class EqualTest: XCTestCase {
...
+        expect(dict) == (["": getString()] as [String: String?])
+
+        // Does not compile with the error:
+        // Cannot convert value of type 'String?' to expected dictionary value type 'String'
+        expect(dict).to(equal(["": getString()])) // This also does not work in latest version v2.9.1
+
+        expect(dict) == ["": getString()]
+
+        let optionalString = getString()
+        expect(dict) == ["": optionalString]
```
Comment (ikesyo) [inline Tests/NimbleTests/Matchers/EqualTest.swift:78]: For operator cases, Swift somehow promotes (implicitly converts) the `dict` of `[String: String]` to `[String: String?]`, but doesn't for the non-operator cases.

https://forums.swift.org/t/implicit-promotion-of-optional/12381

**Comment by younata** [comment]
Adding this to the v10 milestone because we should definitely get this fixed before the next release.

**Comment by younata** [comment]
I created https://github.com/Quick/Nimble/pull/982 to integrate this and actually solve it. I'll close this PR once #982 gets merged.

**Comment by younata** [comment]
Closed now that #982 is in.
