### ISSUE TITLE
compile error on XCode 6.3 beta2

### ISSUE THREAD

**Issue by haifengkao** [Quick/Nimble#116]
I have the following errors when I tried building ReactiveCocoa on XCode 6.3 beta 2
``` 
~/ReactiveCocoa/Carthage/Checkouts/Nimble/Nimble/DSL.swift:4:35: 'autoclosure' attribute is now an attribute of the parameter declaration, not its type
~/ReactiveCocoa/Carthage/Checkouts/Nimble/Nimble/DSL.swift:7:25: Invalid use of non-escaping function in escaping context '() -> T?'
``` 
On XCode 6.3 beta 3, I have 
``` 
~/ReactiveCocoa/Carthage/Checkouts/Nimble/Nimble/Wrappers/AsyncMatcherWrapper.swift:43:35: Extra argument 'timeoutInterval' in call
``` 

It builds fine on XCode 6.1.

**Comment by modocache** [comment]
Thanks for the report, @haifengkao! Which version of Nimble are you using? v0.4.0 supports Swift 1.2/Xcode 6.3, v0.3.0 supports Swift 1.1/Xcode 6.2.

**Comment by haifengkao** [comment]
The version of Nimble is v0.4.0

**Comment by haifengkao** [comment]
My bad. The errors went away with v0.4.0

**Comment by sasijp** [comment]
I am having same problem with Nimble v0.4.0 and Xcode 6.3 Beta 3

** Fetching Alamofire
*** Fetching Quick
*** Fetching Nimble
*** Checking out Alamofire at "2ff5749ffc0425f05a1411b5b6fd2c25241b5b14"
*** Checking out Quick at "v0.3.0"
*** Checking out Nimble at "v0.4.0"
.......
...
```
/Users/jpsasi/Developer/ClientProjects/Playfiks/Playfiks/Carthage/Checkouts/Nimble/Nimble/Wrappers/AsyncMatcherWrapper.swift:43:35: error: extra argument 'timeoutInterval' in call
            to(AsyncMatcherWrapper(
                                  ^
/Users/jpsasi/Developer/ClientProjects/Playfiks/Playfiks/Carthage/Checkouts/Nimble/Nimble/Wrappers/AsyncMatcherWrapper.swift:57:38: error: extra argument 'timeoutInterval' in call
            toNot(AsyncMatcherWrapper(
```

**Comment by modocache** [comment]
@sasijp Sorry about that! I checked, and it looks like v0.4.0 didn't build on the latest Xcode 6.3β3. Please use v0.4.1 instead.

**Comment by sasijp** [comment]
Thank you. It works now with v0.4.1

**Comment by haifengkao** [comment]
Thanks, v0.4.1 solves the error on XCode 6.3 beta 3.
