### ISSUE TITLE
Building test suite fails on Xcode 12 due to not finding XCTest.h header

### ISSUE THREAD

**Issue by bvirlet** [Quick/Nimble#801]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I'm build our test suite for our current project (which builds fine with Xcode 11.4) with Xcode 12 Beta 3. 

### What did you expect to happen?

The tests fail to build with the following error:

```
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/Developer/Library/Frameworks/XCTest.framework/Modules/module.modulemap:2:21: error: umbrella header 'XCTest.h' not found
    umbrella header "XCTest.h"
                    ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "Headers/Nimble-Swift.h"
        ^
/Users/..<shortened>../Vendor/Carthage/Build/iOS/Nimble.framework/Headers/Nimble-Swift.h:199:9: error: could not build module 'XCTest'
@import XCTest;
        ^
<unknown>:0: error: could not build Objective-C module 'Nimble'

```

I have found the [following Apple Forums](https://developer.apple.com/forums/thread/649935?login=true&page=1#623767022) thread which seems relevant but it doesn't give a definite answer. The suggestion solution from Apple engineers seem like a workaround, but also seems to imply that the testing frameworks (such as Quick/Nimble) are missing some settings.

I'm not sure if this is an Xcode 12 Beta 3 issue, or is there something that needs to be fixed. Your advice would be appreciated.

Thanks!

### Environment

List the software versions you're using:

- Quick: *3.0.0*
- Nimble: *8.1.1*
- Xcode Version: *Version 12.0 beta 3 (12A8169g)* 
- Swift Version: *Xcode Default*
- Carthage: *0.35.0* (Use `carthage version` in Terminal)

### Additional information

- Test suite is *hybrid Swift/Objective-C* (but Quick/Nimble are only used in Swift). I don't have the problem with another project's Swift-only test suite.

**Comment by ikesyo** [comment]
Thanks for filing an issue. Could you try #803?

**Comment by bvirlet** [comment]
I seem to be getting the following error if I use #803 (instead of tag v8.1.1):

> Undefined symbols for architecture armv7:
>  "type metadata for Swift._StringObject.Variant", referenced from:
>      outlined init with take of Swift._StringObject.Variant in Stringers.o

**Comment by bvirlet** [comment]
I got rid of the issue on my project by removing the following path "$(SDKROOT)/Developer/Library/Frameworks" from my test target FRAMEWORK_SEARCH_PATHS.

**Comment by ikesyo** [comment]
https://github.com/Quick/Nimble/issues/801#issuecomment-665083858

Looks like the build error is fixed in Xcode 12 beta 4.
