### PR TITLE
Set ENABLE_TESTING_SEARCH_PATHS to YES

### LINKED ISSUE #801: Building test suite fails on Xcode 12 due to not finding XCTest.h header
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I'm build our test suite for our current project (which builds fine with Xcode 11.4) with Xcode 12 Beta 3. 

### What did you expect to happen?

The tests fail to build with the following error:

```
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/Developer/Library/Frameworks/XCTest.framework/Modules/module.modulemap:2:21: error: umbrella header 'XCTest.h' not found
    umbrella header "XCTest.h"
                    ^
<module-includes>:2:9: note: in file included from <module-includes>:2:
#import "Headers/Nimble-Swift.h"
        ^
/Users/..<shortened>../Vendor/Carthage/Build/iOS/Nimble.framework/Headers/Nimble-Swift.h:199:9: error: could not build module 'XCTest'
@import XCTest;
        ^
<unknown>:0: error: could not build Objective-C module 'Nimble'

```

I have found the [following Apple Forums](https://developer.apple.com/forums/thread/649935?login=true&page=1#623767022) thread which seems relevant but it doesn't give a definite answer. The suggestion solution from Apple engineers seem like a workaround, but also seems to imply that the testing frameworks (such as Quick/Nimble) are missing some settings.

I'm not sure if this is an Xcode 12 Beta 3 issue, or is there something that needs to be fixed. Your advice would be appreciated.

Thanks!

### Environment

List the software versions you're using:

- Quick: *3.0.0*
- Nimble: *8.1.1*
- Xcode Version: *Version 12.0 beta 3 (12A8169g)* 
- Swift Version: *Xcode Default*
- Carthage: *0.35.0* (Use `carthage version` in Terminal)

### Additional information

- Test suite is *hybrid Swift/Objective-C* (but Quick/Nimble are only used in Swift). I don't have the problem with another project's Swift-only test suite.

### PR DESCRIPTION
**Pull request by ikesyo**
Sould fix #801.

---

See https://xcodebuildsettings.com/#enable_testing_search_paths and https://developer.apple.com/documentation/xcode-release-notes/xcode-11_4-release-notes:

> Xcode introduced an “Enable Testing Search Paths” build setting to improve support for test support frameworks and libraries. This build setting is on by default for test bundle targets, as well as for targets which explicitly include XCTest.framework in their “Link Binary With Libraries” list. Source files in such targets can now import XCTest without setting any custom search paths. (51117167)

### CODE REVIEW

**Comment by ikesyo** [comment]
The podspec should be updated too.
