### PR TITLE
Adds matchers for Swift 5 Result type

### PR DESCRIPTION
**Pull request by xzeror**
Swift 5 adds common Result type. It's useful to have matchers out of the box in Nimble. 
This PR adds matchers beSuccess and beFailure. This is purely additive changes with full test coverage. Also added some code samples into Readme.

 - [✅ ] Does this have tests?
 - [✅ ] Does this have documentation?
 - [ ❌] Does this break the public API (Requires major version bump)?
 - [✅ ] Is this a new feature (Requires minor version bump)?

### CODE REVIEW

File: Tests/NimbleTests/XCTestManifests.swift [hunk 1]
```diff
@@ -344,6 +344,27 @@ extension UserDescriptionTest {
     ]
 }
 
+#if swift(>=5)
+extension BeSuccessTest {
```
Comment (ikesyo) [inline Tests/NimbleTests/XCTestManifests.swift]: This file is generated by `swift test --generate-linuxmain` so please don't edit manually.

Comment (xzeror) [reply Tests/NimbleTests/XCTestManifests.swift]: Ok. Fixed that.

Comment (xzeror) [reply Tests/NimbleTests/XCTestManifests.swift]: @ikesyo I think it's never worked automatically. Because in order to ```swift test --generate-linuxmain``` to work the code of test target must be compiled, and it can't be compiled because new test class doesn't conform to XCTestCaseProviderStatic through XCTestCaseProvider because ```__allTests``` property haven't been generated yet. So the manual addition of extension into XCTestManifests.swift for new test file with empty ```__allTests``` array is necessary. In fact if you delete or rename any existing test you would have to manually delete or rename it in XCTestManifests.swift. 
Secondly ```swift test``` generates slightly different code in swift 5. Specifically it generates all tests property with test class name suffix ```static let __allTests__BeNilTest``` so it breaks all tests because all test class become nonconforming to XCTestCaseProviderStatic protocol. So it will need manual editing of XCTestManifests or modifying all test class and removing conformation to XCTestCaseProvider, effectively removing detecting of missing test cases.
If we will go the second way, removing XCTestCaseProvider, we can still automate generation of XCTestManifests via running ```swift test --generate-linuxmain``` before every test and excluding XCTestManifests.swift from VCS. I've done that in [here](https://github.com/xzeror/Nimble/tree/result_matchers_and_swift_test_autogeneration). If it should be done in separate request tell me please.
So I think that most straight way is to merge this PR with manually edited XCTestManifests. And then move to full XCTestManifests autogeneration.

Comment (ikesyo) [reply Tests/NimbleTests/XCTestManifests.swift]: Thanks for letting me know that. I didn't updated the manifest with Swift 5 yet, so didn't know that. But

> If we will go the second way, removing XCTestCaseProvider, we can still automate generation of XCTestManifests via running swift test --generate-linuxmain before every test and excluding XCTestManifests.swift from VCS. I've done that in here.

This should not work because

- `swift test --generate-linuxmain` only works on macOS (thanks to Objective-C runtime)
- and LinuxMain is for Linux, not for SwiftPM on maxOS so we can't use the file without commiting it
  - If `swift test --generate-linuxmain` works on Linux, that means that automatic discovery works so there is no need to prepare the manifest file. That is because LinuxMain exists

Comment (ikesyo) [reply Tests/NimbleTests/XCTestManifests.swift]: TL;DR

- Generate LinuxMain on macOS
- Use LinuxMain (which is generated on macOS) on Linux

That is the workflow.

Comment (xzeror) [reply Tests/NimbleTests/XCTestManifests.swift]: @ikesyo ok. Got it. So should I regenerate XCTestManifests using Swift 5 toolchain and remove XCTestCaseProvider stuff in this PR (I guess this won't be able to be build on Swift 4.2.1) or try to resolve build issues with manually edited current XCTestManifests and move XCTestManifests to Swift 5 in separate PR?

File: Sources/Nimble/Matchers/BeResult.swift [hunk 2]
```diff
@@ -0,0 +1,37 @@
+import Foundation
+
+///
+/// A Nimble matcher for Result that succeeds when the actual value is success
+///
+/// You can pass a closure to do any arbitrary custom matching
+/// to the value inside result. The closure only gets called when result is success.
+#if swift(>=5)
+@available(swift 5)
+public func beSuccess<T>(test: ((T) -> Void)? = nil) -> Predicate<Result<T, Error>> {
```
Comment (kamitchell) [inline Sources/Nimble/Matchers/BeResult.swift]: This is awesome and I want it! So I put the source into my project for now, but I get this compilation error:

```
Predicate<Result<Double, Error>>' is not convertible to 'Predicate<Result<Double, CalculationError>>
```

...because `Result<Double, CalculationError>` is what I declared for that type in my program. The `Failure` type of `Result` doesn't necessarily have to conform to `Error`.

It works better for me if I let the `Failure` type of `Result` be parameterized as well, by changing this line to:

```
public func beSuccess<T, E>(test: ((T) -> Void)? = nil) -> Predicate<Result<T, E>> {
```

**Comment by dtrenz** [comment]
For what it's worth, I'm using these as my local custom `Result` type matchers, in case someone wants to steal them:
```swift
func beFailure<Success, Failure>() -> Predicate<Result<Success, Failure>> {
    return Predicate.simple("be failure") { actualExpression in
        guard let actual = try actualExpression.evaluate(), case .failure = actual else {
            return .doesNotMatch
        }
        return .matches
    }
}

func beSuccess<Success, Failure>() -> Predicate<Result<Success, Failure>> {
    return Predicate.simple("be success") { actualExpression in
        guard let actual = try actualExpression.evaluate(), case .success = actual else {
            return .doesNotMatch
        }
        return .matches
    }
}
```

**Comment by ikesyo** [comment]
Sorry for the late, I'm rebooting this now for Nimble v9.

File: Sources/Nimble/Matchers/BeResult.swift [hunk 3]
```diff
@@ -0,0 +1,33 @@
+import Foundation
+
+///
+/// A Nimble matcher for Result that succeeds when the actual value is success
+///
+/// You can pass a closure to do any arbitrary custom matching
+/// to the value inside result. The closure only gets called when result is success.
+public func beSuccess<T>(test: ((T) -> Void)? = nil) -> Predicate<Result<T, Error>> {
```
Comment (ikesyo) [inline Sources/Nimble/Matchers/BeResult.swift:8]:
```suggestion
public func beSuccess<Success, Failure>(test: ((Success) -> Void)? = nil) -> Predicate<Result<Success, Failure>> {
```

File: Sources/Nimble/Matchers/BeResult.swift [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+        return PredicateResult(status: .matches, message: message)
+    }
+}
+
+///
+/// A Nimble matcher for Result that succeeds when the actual value is failure
+///
+/// You can pass a closure to do custom matching for the error inside result.
+/// The closure only gets called when result is failure.
+public func beFailure<T>(test: ((Error) -> Void)? = nil) -> Predicate<Result<T, Error>> {
```
Comment (ikesyo) [inline Sources/Nimble/Matchers/BeResult.swift:24]:
```suggestion
public func beFailure<Success, Failure>(test: ((Failure) -> Void)? = nil) -> Predicate<Result<Success, Failure>> {
```

File: Sources/Nimble/Matchers/BeResult.swift [hunk 5]
```diff
@@ -0,0 +1,33 @@
+import Foundation
+
+///
+/// A Nimble matcher for Result that succeeds when the actual value is success
+///
+/// You can pass a closure to do any arbitrary custom matching
+/// to the value inside result. The closure only gets called when result is success.
+public func beSuccess<T>(test: ((T) -> Void)? = nil) -> Predicate<Result<T, Error>> {
+    return Predicate.define("be <success>") { expression, message in
```
Comment (ikesyo) [inline Sources/Nimble/Matchers/BeResult.swift:9]:
```suggestion
    return Predicate.define("be <success(\(Success.self))>") { expression, message in
```

File: Sources/Nimble/Matchers/BeResult.swift [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+    }
+}
+
+///
+/// A Nimble matcher for Result that succeeds when the actual value is failure
+///
+/// You can pass a closure to do custom matching for the error inside result.
+/// The closure only gets called when result is failure.
+public func beFailure<T>(test: ((Error) -> Void)? = nil) -> Predicate<Result<T, Error>> {
+    return Predicate.define("be <failure>") { expression, message in
```
Comment (ikesyo) [inline Sources/Nimble/Matchers/BeResult.swift:25]:
```suggestion
    return Predicate.define("be <failure(\(Failure.self))>") { expression, message in
```

**Review by ikesyo — APPROVED** [review]
