### PR TITLE
[7.x][Predicate] Override `NSObject.hash` over `Hashable.hashValue`

### LINKED ISSUE #625: Does not compile on Xcode 10.2 beta  (10P82s)
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
Tried to build unit tests that use Quick and Nimble on Xcode 10.2 beta.

### What did you expect to happen?
Successful build. 

### What actually happened instead?
Line 314 of Predicate.swift has a compilation error: 
"Predicate.swift:314:25: Overriding non-open property outside of its defining module.
Overriding non-@objc declarations from extensions is not supported"

### Environment

List the software versions you're using:

Using Nimble (7.3.2)
Using Quick (1.3.2)
 - Xcode Version: 10.2 beta 10P82s)
 - Swift Version: 4.2

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.5.3

### PR DESCRIPTION
**Pull request by ikesyo**
Closes #625.

This had been addressed on master by https://github.com/Quick/Nimble/pull/604.

### CODE REVIEW

**Comment by ikesyo** [comment]
I'll merge this once CI passes and cut v7.3.3.
