### ISSUE TITLE
Nimble 0.4.0 does not compile with Xcode 6.2

### ISSUE THREAD

**Issue by dfreniche** [Quick/Nimble#112]
Problem: Nimble does not compile in a new project using CocoaPods. Cloned the Nimble repo, does not compile either

- using Xcode 6.2 (build 6C131e)

Steps in Terminal:
1. clone Nimble repo: `git clone https://github.com/Quick/Nimble.git`
2.`open Nimble.xcodeproj/`

When building I get lots of errors, like the following

```
/nimble/Nimble/Nimble/Matchers/BeLessThan.swift:32:53: error: expected type after 'as'
            let expr = actualExpression.cast { $0 as! NMBComparable? }
                                                    ^
/nimble/Nimble/Nimble/Matchers/RaisesException.swift:177:35: error: expected '{' after 'if' condition
        } else if let name = _name, reason = _reason, userInfo = _userInfo {
                                  ^
/nimble/Nimble/Nimble/Matchers/RaisesException.swift:177:76: error: braced block of statements is an unused closure
        } else if let name = _name, reason = _reason, userInfo = _userInfo {
                                                                           ^
/nimble/Nimble/Nimble/Matchers/RaisesException.swift:179:10: error: consecutive statements on a line must be separated by ';'
        } else if let name = _name, reason = _reason {
         ^
         ;



```

**Comment by dfreniche** [comment]
Looks like a problem in the last v0.4.0 version.

doing `git checkout tags/v0.3.1` it compiles fine

**Comment by modocache** [comment]
@dfreniche Thanks for the heads up! This isn't a bug, though: Nimble `v0.4.0` supports Swift 1.2 (included with the Xcode 6.3 betas). If you'd like to use Nimble with Swift 1.1 (included in Xcode 6.2), use `v0.3.*`. :+1: :sparkles:
