### ISSUE TITLE
Does not compile on Xcode 10.2 beta  (10P82s)

### ISSUE THREAD

**Issue by jmfriend** [Quick/Nimble#625]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
Tried to build unit tests that use Quick and Nimble on Xcode 10.2 beta.

### What did you expect to happen?
Successful build. 

### What actually happened instead?
Line 314 of Predicate.swift has a compilation error: 
"Predicate.swift:314:25: Overriding non-open property outside of its defining module.
Overriding non-@objc declarations from extensions is not supported"

### Environment

List the software versions you're using:

Using Nimble (7.3.2)
Using Quick (1.3.2)
 - Xcode Version: 10.2 beta 10P82s)
 - Swift Version: 4.2

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.5.3

**Comment by ikesyo** [comment]
Okay so we should override `NSObject.hash` here instead of `Hashable.hashValue`.

- https://github.com/Quick/Nimble/blob/df937ffd185b3dd1a44e0c234121cf826b599eb4/Sources/Nimble/Matchers/Predicate.swift#L314

This had been addressed on master by https://github.com/Quick/Nimble/pull/604 but not on 7.x-branch.

**Comment by ikesyo** [comment]
Should be addressed in [v7.3.3](https://github.com/Quick/Nimble/releases/tag/v7.3.3).

**Comment by jmfriend** [comment]
Fantastic. Many thanks. Quick & Nimble are great.

**Comment by makma** [comment]
Thank you for implementing this feature and your pull request! Your work is appreciated. Just one note for the future - do not use force push on branches you share with somebody else. This also applies to [pull requests](https://help.github.com/en/articles/about-pull-requests). 

> When pushing commits to a pull request, don't force push. Force pushing can corrupt your pull request.

Thank you.
