### PR TITLE
Fixes the build on Xcode 14.3b2

### PR DESCRIPTION
**Pull request by dymv**
### What behavior was changed?
None. 

### What code was refactored / updated to support this change?
Updates made to ObjC func implementations. More info: https://developer.apple.com/forums/thread/725753

### What issues are related to this PR? Or why was this change introduced?
Building Nimble in Xcode 14.3b2 (14E5207e) is failing due to 

```
.../nimble/Sources/NimbleObjectiveC/DSL.m:71:41: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
NIMBLE_EXPORT NMBPredicate *NMB_beTruthy() {
                                        ^
                                         void
```
---
- [x] Does this have tests? — NO
- [x] Does this have documentation? — NO
- [x] Does this break the public API (Requires major version bump)? — NO
- [x] Is this a new feature (Requires minor version bump)? — NO

### CODE REVIEW

**Review by younata — APPROVED** [review]
... really? Come on Apple.

**Comment by dymv** [comment]
Thank you @younata 🙇

**Comment by einar-notland** [comment]
@younata Any plans for a release with this included? I mean now that Xcode 14.3 is out of beta.

**Comment by younata** [comment]
> @younata Any plans for a release with this included? I mean now that Xcode 14.3 is out of beta.

Thanks for the reminder! v11.2.2 is now released and includes this fix!
